{{- if and .Values.secrets (not .Values.application.disabled) }}
{{- range $name, $object := .Values.secrets }}

{{- if eq $object.type "external" }}
{{- $ssr := default dict $object.secretStoreRef }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $name }}
spec:
  {{- include "template.field" (dict "Name" "refreshInterval" "Default" $object.refreshInterval "Optional" "1m") | indent 2 }}
  {{- include "template.field" (dict "Name" "secretStoreRef" "Default" $object.secretStoreRef "Optional" $.Values.secretStoreRef) | indent 2 }}
  target:
    name: {{ $name }}
  {{- include "template.field" (dict "Name" "dataFrom" "Default" $object.dataFrom "Optional" (dict)) | indent 2 }}

{{- else }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
type: Opaque
stringData:
  {{- range $key, $value := $object.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
---
{{- end }}
{{- end }}
