{{- if not .Values.application.disabled }}
{{- range $name, $object := .Values.serviceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  {{- include "template.field" (dict "Name" "annotations" "Default" $object.annotations "Optional" dict) | indent 2 }}
---
{{- end }}
{{- end }}
