default:
  image:
    repository: crusaderx2/utils
    version: latest
  deployments:
    # default
    baz-default:
      containers:
      - name: baz
        envFrom:
        - configMapRef:
            name: baz-default

    # heavy
    baz-heavy:
      configMap:
        # ovveride configMap defaults for heavy purpose
        QUEUE_NAME: queue-heavy
        QUEUE_BATCH_SIZE: 500
      containers:
      - name: baz
        envFrom:
        - configMapRef:
            name: baz-heavy
      # override default persistance-claim with another claim
      volumes:
        - name: persistance-claim
          persistentVolumeClaim:
            claimName: persistance-heavy-claim
