annotations:
  reloader.stakater.com/auto: "true"
application:
  kind: default # REQUIRED
  name: default # REQUIRED
common:
  domain: default
dnsConfig:
  options:
    - name: ndots
      value: "1"
image:
  registry: default
  repository: default
  version: latest
rollout:
  strategy: gradual
scalingStrategy:
  strategy: accurate
secretStoreRef:
  name: default
  kind: ClusterSecretStore
strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate

