default:
  image:
    repository: crusaderx2/utils
    version: latest
  deployments:
    foo:
      # override existing label key with different value
      # be aware that this will affect service selector,
      # so we have to modify it too
      labels:
        example.foo.service: override
      containers:
      - name: foo
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 2
            memory: 512Mi
  services:
    foo:
      ports:
        - name: http
          port: 80
          targetPort: 8080
      selector:
        example.foo.service: override
