name: ci unit tests

on:
  push:
    paths:
      - 'examples/**'
      - 'library/**'
  pull_request:
    paths:
      - 'examples/**'
      - 'library/**'

jobs:
  unittests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        chart: [foo, bar, baz]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/composite/unittest
        with:
          chart: ${{ matrix.chart}}
